services:
  app:
    image: php:8.2-fpm
    container_name: app
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    networks:
      - app-network
  webserver:
    image: nginx:latest
    container_name: webserver
    working_dir: /var/www
    volumes:
      - ./src:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
    networks:
      - app-network
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: 
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  mysql-data:
